       IDENTIFICATION DIVISION.
       PROGRAM-ID. GENPROG.
       AUTHOR. COBOL GENERATOR.
       DATE-WRITTEN. 2025-05-10.

       DATA DIVISION.
       WORKING-STORAGE SECTION.
       01 GREETING PIC X(30) VALUE "HELLO FROM GENERATED COBOL"
       01 COUNTER PIC 9(3) VALUE 0
       01 MAX-COUNT PIC 9(3) VALUE 5
       01 RESULT-TABLE
       05 RESULT-ENTRY PIC X(50) VALUE "SPACES"
       05 RESULT-VALUES
       10 RESULT-VALUE PIC 9(5) VALUE 0
       10 RESULT-TEXT PIC X(20) VALUE "SPACES"

       PROCEDURE DIVISION.
       MAIN-PARA.
           DISPLAY GREETING
           PERFORM PROCESS-DATA UNTIL COUNTER > MAX-COUNT
           DISPLAY "PROCESSING COMPLETE"
           STOP RUN
       PROCESS-DATA.
           ADD 1 TO COUNTER
           COMPUTE RESULT-VALUE = COUNTER * 10
           MOVE "ITERATION" TO RESULT-TEXT
           DISPLAY "PROCESSED ITEM: " COUNTER
           STOP RUN.
