# COBOL Extraction Configuration
# This file defines what elements to extract from COBOL programs

output_format: json  # Output format (json or xml)

extraction:
  identification:
    enabled: true
    elements:
      - program_id
      - author
      - date_written
      - date_compiled
      - security
      - installation
  
  environment:
    enabled: true
    elements:
      - source_computer
      - object_computer
      - special_names
  
  data:
    enabled: true
    sections:
      - name: working_storage
        enabled: true
        extract_level_numbers: [01, 05, 10, 15, 20, 77]
        extract_fields:
          - name
          - level
          - picture
          - value
          - usage
      - name: file_section
        enabled: true
        extract_fields:
          - name
          - level
          - organization
          - access_mode
      - name: linkage_section
        enabled: true
        extract_fields:
          - name
          - level
          - picture
  
  procedure:
    enabled: true
    elements:
      - paragraphs
      - sections
    statement_types:
      - PERFORM
      - IF
      - MOVE
      - COMPUTE
      - CALL
      - DISPLAY
    extract_comments: true
    
  custom_analysis:
    enabled: true
    elements:
      - variable_usage
      - paragraph_calls
      - data_dependencies
